---
name: TestRun

on:
  workflow_dispatch:
    inputs:
      id:
        description: "Your 1.1.1.1/WARP+ ID"
        required: true
      iter:
        description: "Iterations (Target Referrals to be generated)"
        required: true
        default: "100"
      interv:
        description: "Interval per Referral"
        required: true
        default: "5"
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Run
        run: bash warp-up.sh --id ${{ github.event.inputs.id }} --iterations ${{ github.event.inputs.iter }} --interval ${{ github.event.inputs.interv }} --disclaimer || exit 1
